CREATE TABLE users
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id     VARCHAR(255),
    email       VARCHAR(255),
    api_key     VARCHAR(255),
    webhook_url VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);