CREATE TABLE events
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_id   VARCHAR(255),
    user_id    BIGINT,
    status     VARCHAR(255),
    payload    VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_events PRIMARY KEY (id)
);

ALTER TABLE users
    ADD created_at TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE events
    ADD CONSTRAINT FK_EVENTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);