CREATE TABLE delivery_attempts
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_id  VARCHAR(255),
    attempt   INTEGER,
    success   BOOLEAN,
    error     VARCHAR(255),
    timestamp TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_delivery_attempts PRIMARY KEY (id)
);